services:
  Nng\Nnhelpers\EventListener\ClearCacheEvent:
    tags:
      - name: event.listener
        method: handleEvent
        identifier: 'myListener'
        before: 'redirects, anotherIdentifier'
        event: TYPO3\CMS\Core\Cache\Event\CacheFlushEvent